name: Riscv64 Build Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # ensure the toolchain is cached
  ensure-toolchain:
    uses: ./.github/workflows/cache-toolchain.yml
  
  build:

    runs-on: ubuntu-latest
    needs: [ensure-toolchain]

    steps:
    - uses: actions/checkout@v3

    
    - name: Cache build tools
      id: dragon-boot-cache-build-tools
      uses: actions/cache@v3
      env:
          cache-name: dragon-boot-cache-build-tools
      with:
        path: |
          ~/.cargo
          ~/.rustup
          ~/.bashrc
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.github/workflows/cache-toolchain.yml') }}
      
    
    - name: Riscv64 Build Check
      run: |
            ARCH=riscv64 make
